# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Erdlens < Formula
  desc "Interactive, git-friendly ER diagrams for relational databases."
  homepage "https://github.com/erdlens/erdlens"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erdlens/erdlens/releases/download/v0.3.0/erdlens_0.3.0_darwin_amd64.tar.gz"
      sha256 "cd78026a68aae27336b9cf38cace7920809af2b580d005cff20f7ad884218c38"

      define_method(:install) do
        bin.install "erdlens"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/erdlens/erdlens/releases/download/v0.3.0/erdlens_0.3.0_darwin_arm64.tar.gz"
      sha256 "e00f441e48c0c72206c2fc05f3ca811abe8fba55bdd93d03b53ed50465520d16"

      define_method(:install) do
        bin.install "erdlens"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/erdlens/erdlens/releases/download/v0.3.0/erdlens_0.3.0_linux_amd64.tar.gz"
      sha256 "57aa71a0b8d735a1d7ca082f21b745fc5d9fa543ba1e35940c56679fe5e6038f"
      define_method(:install) do
        bin.install "erdlens"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/erdlens/erdlens/releases/download/v0.3.0/erdlens_0.3.0_linux_arm64.tar.gz"
      sha256 "56dbc224bdd3b047beaaca5f3a17ffd94e09cd250e081895ba75a647ea8bffc7"
      define_method(:install) do
        bin.install "erdlens"
      end
    end
  end

  test do
    system "#{bin}/erdlens", "version"
  end
end
