# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Erdlens < Formula
  desc "Interactive, git-friendly ER diagrams for relational databases."
  homepage "https://github.com/erdlens/erdlens"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erdlens/erdlens/releases/download/v0.1.1/erdlens_0.1.1_darwin_amd64.tar.gz"
      sha256 "f44b01aae528ac0b93ad6ee71fa3ad68b3a56f5a268a5c33aaa2eb791cfe701b"

      define_method(:install) do
        bin.install "erdlens"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/erdlens/erdlens/releases/download/v0.1.1/erdlens_0.1.1_darwin_arm64.tar.gz"
      sha256 "7b1c09ea38b19c41b3a7e3e5c705963d7fbc1ecd1081dd3f17d188a6decb28b1"

      define_method(:install) do
        bin.install "erdlens"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/erdlens/erdlens/releases/download/v0.1.1/erdlens_0.1.1_linux_amd64.tar.gz"
      sha256 "9c57b2442b2f50d065877ca676e0a56c12a9057feb58d6a2276cf1f9d5d96653"
      define_method(:install) do
        bin.install "erdlens"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/erdlens/erdlens/releases/download/v0.1.1/erdlens_0.1.1_linux_arm64.tar.gz"
      sha256 "2c6e8e8822c211158fb7d18da251c1a997db738edcf572e1f7afe0e5647dde8c"
      define_method(:install) do
        bin.install "erdlens"
      end
    end
  end

  test do
    system "#{bin}/erdlens", "version"
  end
end
